import { test } from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import path from 'node:path';
import {
  createOvernightGraph,
  FileCheckpointSaver,
  OvernightStateAnnotation
} from '../lib/subagents/supervisor';
import { WorkerPool } from '../lib/subagents/workerPool';

test('Fix 1 — LangGraph Real Nodes & File-Backed Checkpointing Suite', async (t) => {
  const testCheckpointDir = path.resolve(process.cwd(), '.tmp-lg-nodes-test');
  if (!fs.existsSync(testCheckpointDir)) {
    fs.mkdirSync(testCheckpointDir, { recursive: true });
  }

  t.after(() => {
    try {
      fs.rmSync(testCheckpointDir, { recursive: true, force: true });
    } catch {}
  });

  await t.test('executes graph through all five real nodes in order (planner -> explorer -> builder -> critic -> recorder)', async () => {
    const checkpointer = new FileCheckpointSaver(testCheckpointDir);
    const workerPool = new WorkerPool();
    const taskId = `lg-task-${Date.now()}`;

    const graph = createOvernightGraph({
      checkpointer,
      workerPool
    });
    const app = graph.compile({ checkpointer });

    const executedSteps: string[] = [];
    const stream = await app.stream(
      {
        taskId,
        goal: 'Build synthetic calculator with add and subtract functions',
        toolchain: 'node:22',
        status: 'queued',
        currentMilestoneIndex: 0,
        milestones: [],
        checkpoints: [],
        ambiguityFlags: [],
        journal: [],
        nodeHistory: []
      },
      { configurable: { thread_id: taskId } }
    );

    for await (const chunk of stream) {
      const stepName = Object.keys(chunk)[0];
      executedSteps.push(stepName);
    }

    // 1. Assert state transitions through all five nodes in order
    assert.deepStrictEqual(executedSteps, [
      'planner',
      'explorer',
      'builder',
      'critic',
      'recorder'
    ]);

    // 2. Assert final state contains milestones generated by planner, diff by builder, verified by critic
    const finalState = await app.getState({ configurable: { thread_id: taskId } });
    assert.strictEqual(finalState.values.status, 'completed');
    assert(finalState.values.milestones.length >= 3);
    assert.deepStrictEqual(finalState.values.nodeHistory, [
      'planner',
      'explorer',
      'builder',
      'critic',
      'recorder'
    ]);

    // 3. Assert checkpoint was written to disk by LangGraph checkpointer
    const checkpointFile = checkpointer.getFilePath(taskId);
    assert(fs.existsSync(checkpointFile), `Expected ${checkpointFile} to exist on disk`);
    const fileContent = fs.readFileSync(checkpointFile, 'utf8');
    assert(fileContent.length > 50, 'Checkpoint file should contain serialized state');
  });

  await t.test('kills graph mid-run and resumes through LangGraph checkpointer to completion', async () => {
    const checkpointer1 = new FileCheckpointSaver(testCheckpointDir);
    const workerPool1 = new WorkerPool();
    const taskId = `lg-crash-task-${Date.now()}`;

    const graph1 = createOvernightGraph({
      checkpointer: checkpointer1,
      workerPool: workerPool1
    });
    const app1 = graph1.compile({ checkpointer: checkpointer1 });

    const stepTrail1: string[] = [];
    const stream1 = await app1.stream(
      {
        taskId,
        goal: 'Build synthetic microservice endpoint',
        toolchain: 'node:22',
        status: 'queued',
        currentMilestoneIndex: 0,
        milestones: [],
        checkpoints: [],
        ambiguityFlags: [],
        journal: [],
        nodeHistory: []
      },
      { configurable: { thread_id: taskId } }
    );

    // Simulate worker crash after explorer node completes
    for await (const chunk of stream1) {
      const step = Object.keys(chunk)[0];
      stepTrail1.push(step);
      if (step === 'explorer') {
        // Crash / kill mid-run!
        break;
      }
    }

    assert.deepStrictEqual(stepTrail1, ['planner', 'explorer']);

    // Assert checkpoint file was persisted mid-run
    const checkpointFile = checkpointer1.getFilePath(taskId);
    assert(fs.existsSync(checkpointFile), 'Checkpoint file must be written mid-run before crash');

    // Simulate new supervisor process starting up with a fresh checkpointer and graph instance
    const checkpointer2 = new FileCheckpointSaver(testCheckpointDir);
    const workerPool2 = new WorkerPool();
    const graph2 = createOvernightGraph({
      checkpointer: checkpointer2,
      workerPool: workerPool2
    });
    const app2 = graph2.compile({ checkpointer: checkpointer2 });

    // Verify next scheduled node from saved checkpoint is builder
    const stateBeforeResume = await app2.getState({ configurable: { thread_id: taskId } });
    assert.deepStrictEqual(stateBeforeResume.next, ['builder']);

    // Resume execution from checkpoint to completion
    const stepTrail2: string[] = [];
    const stream2 = await app2.stream(null, { configurable: { thread_id: taskId } });
    for await (const chunk of stream2) {
      const step = Object.keys(chunk)[0];
      stepTrail2.push(step);
    }

    // Assert resumed execution picked up at builder, critic, recorder
    assert.deepStrictEqual(stepTrail2, ['builder', 'critic', 'recorder']);

    const finalResumedState = await app2.getState({ configurable: { thread_id: taskId } });
    assert.strictEqual(finalResumedState.values.status, 'completed');
    assert.deepStrictEqual(finalResumedState.values.nodeHistory, [
      'planner',
      'explorer',
      'builder',
      'critic',
      'recorder'
    ]);
  });
});
